### ISSUE TITLE
Error: not found https://github.com/Aave/aave-protocol/contracts/flashloans/Flashloan.sol deploying on remix

### ISSUE THREAD

**Issue by Hatem1234h** [madoibito80/Blog#2]
am working on flash loan on remix i get this with every deployning :-

Error: not found https://github.com/Aave/aave-protocol/contracts/flashloans/Flashloan.sol

any one know how to solve it?

**Comment by madoibito80** [comment]
Hi, you should use the latest version of aave, that is v3 here: https://github.com/aave/aave-v3-core/tree/master/contracts/flashloan
