### ISSUE TITLE
i cuud not deploy it in Remix. / flash loan from DODO

### ISSUE THREAD

**Issue by Hatem1234h** [madoibito80/Blog#3]
// SPDX-License-Identifier: MIT
pragma solidity 0.8.0;

interface IERC20 {
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function approve(address spender, uint256 amount) external returns (bool);
}

interface IFlashLoanReceiver {
    function execute(address token, uint256 amount, uint256 fee, bytes calldata data) external;
}

interface IPegStabilityModule {
    function mint(uint256 daiAmount) external;
    function redeem(uint256 psmAmount) external returns (uint256 daiAmount);
}

interface IDODO {
    function flashLoan(address receiver, address token, uint256 amount, bytes calldata data) external;
}

interface IDLP {
    function flashLoan(address receiver, address token, uint256 amount, bytes calldata data) external;
}

interface IBalancer {
    function flashLoan(address receiver, address token, uint256 amount, bytes calldata data) external;
}

contract FlashLoanLoop {
    address public owner;
    address public daiAddress;
    address public usdcAddress;
    address public psmAddress;
    address public dodoAddress;
    address public dlpAddress;
    address public balancerAddress;

    constructor(
        address _owner,
        address _daiAddress,
        address _usdcAddress,
        address _psmAddress,
        address _dodoAddress,
        address _dlpAddress,
        address _balancerAddress
    ) {
        owner = _owner;
        daiAddress = _daiAddress;
        usdcAddress = _usdcAddress;
        psmAddress = _psmAddress;
        dodoAddress = _dodoAddress;
        dlpAddress = _dlpAddress;
        balancerAddress = _balancerAddress;
    }

    function startFlashLoanLoop(uint256 loops) external {
        require(msg.sender == owner, "only owner can execute");
        for (uint256 i = 0; i < loops; i++) {
            // Perform a flash loan from DODO
            bytes memory data = abi.encode(i);
            IDODO(dodoAddress).flashLoan(address(this), usdcAddress, 1000000, data);
        }
    }

    function execute(address token, uint256 amount, uint256 fee, bytes calldata data) external {
        require(msg.sender == dodoAddress, "only DODO can execute");
        require(token == usdcAddress, "only USDC supported");
        require(amount == 1000000, "only 1M USDC supported");
        uint256 usdcBalance = IERC20(usdcAddress).balanceOf(address(this));
        uint256 daiBalance = usdcBalance * 100 / 99;

        // Mint PSM tokens
        IERC20(daiAddress).approve(psmAddress, daiBalance);
        IPegStabilityModule(psmAddress).mint(daiBalance);

        // Perform some arbitrage using the flash loaned assets
        // ...

        // Redeem PSM tokens
        uint256 psmTokens = IERC20(psmAddress).balanceOf(address(this));
        uint256 daiAmount = IPegStabilityModule(psmAddress).redeem(psmTokens);
        IERC20(daiAddress).transfer(msg.sender, daiAmount);

        // Pay back flash loan
        uint256 total = amount + fee;
        IERC20(usdcAddress).transfer(dodoAddress, total);
    }
}

**Comment by madoibito80** [comment]
Sorry, it seems that the issue is not caused by the code I published.
